icon: assets/icons/icon.png
summary: An application to stream Music
group: Application/Multimedia
vendor: anandnet
packager: anandnet
license: GPLv3
url: https://github.com/Arturo254/OpenTune

requires:
  - mpv-libs
  - libappindicator

display_name: OpenTune Desktop

keywords:
  - Opensource
  - Music
  - Streaming
  - Flutter

generic_name: Music Application

categories:
  - Music

startup_notify: true