name: Build Windows exe 
on: workflow_dispatch
  
jobs:

  build-windows-exe:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.3'

      - name: Update lang data
        working-directory: "${{ github.workspace }}"
        run: dart localization/generator.dart

      - name: Set update check flag to true
        working-directory: "${{ github.workspace }}/lib/utils"
        run: echo "const updateCheckFlag = true;" > update_check_flag_file.dart
        
      - name: Build windows exe package
        working-directory: "${{ github.workspace }}"
        run: |
          flutter clean
          dart pub global activate flutter_distributor
          flutter_distributor package --platform windows --targets exe
          
      - name: Set up osslsigncode
        run: |
          Invoke-WebRequest -Uri "https://github.com/mtrojnar/osslsigncode/releases/download/2.9/osslsigncode-2.9-windows-x64-mingw.zip" -OutFile "osslsigncode.zip"
          Expand-Archive -Path "osslsigncode.zip" -DestinationPath "osslsigncode"
          Add-Content -Path $env:GITHUB_PATH -Value "${{ github.workspace }}\osslsigncode"
      
      - name: Make signing dir
        working-directory: "${{ github.workspace }}"
        run: mkdir signed

      - name: Decode certificate and key
        working-directory: "${{ github.workspace }}/signed"
        run: |
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.CERT_PEM }}")) | Out-File -FilePath cert.pem -Encoding ASCII
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.KEY_PEM }}")) | Out-File -FilePath key.pem -Encoding ASCII

      - name: Sign executable
        working-directory: "${{ github.workspace }}/signed"
        run: |
          osslsigncode sign -certs cert.pem -key key.pem -in  "${{ github.workspace }}/dist/harmonymusic*.exe" -out harmony_music_signed.exe

      # Step 5: Verify the signature
      - name: Verify signature
        working-directory: "${{ github.workspace }}/signed"
        run: |
          osslsigncode verify harmony_music_signed.exe
          
      - name: Upload Windows exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: Harmony music windows exe
          path: "${{ github.workspace }}/signed/*.exe"
